# Custom Appveyor settings
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Desktop
    Test: Full
    StandardName: PesterHelpers
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Core
    Test: Full
    StandardName: PesterHelpers
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Desktop
    Test: Norm
    StandardName: PesterHelpers
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Core
    Test: Norm
    StandardName: PesterHelpers
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Desktop
    Test: Min
    StandardName: PesterHelpers
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Core
    Test: Min
    StandardName: PesterHelpers
matrix:
  # immediately finish build on failure
  fast_finish: true

# Scripts that run after cloning
install:
  - ps: Install-Module -Name InvokeBuild, PowerShellGet, Pester, PSScriptAnalyzer -SkipPublisherCheck -Force
build_script:
  - ps: |
      $ErrorActionPreference = 'Stop'
      $buildScript = ".\build.ps1"
      Invoke-Build -File $buildScript
      Compress-Archive -Path ".\bin\$Env:APPVEYOR_PROJECT_NAME" -DestinationPath ".\$Env:APPVEYOR_PROJECT_NAME.zip"
      Push-AppveyorArtifact ".\$Env:APPVEYOR_PROJECT_NAME.zip"